/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao.panels;

import br.univali.questoes.QuestoesDerivadas;
import java.util.List;

/**
 *
 * @author Alisson
 */
public class DerivadaPanel extends javax.swing.JPanel {

    /**
     * Creates new form DerivadaPanel
     */
    public DerivadaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        respostaDerivadaArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jfuncaoderivada = new javax.swing.JComboBox();
        jPanel47 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tipoDerivada = new javax.swing.JComboBox();
        jPanel46 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        taxaIncremento = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        valorX = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        hInicial = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        taxaErro = new javax.swing.JTextField();
        jPanel45 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoResposta = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new java.awt.BorderLayout(4, 4));

        respostaDerivadaArea.setColumns(20);
        respostaDerivadaArea.setRows(5);
        jScrollPane6.setViewportView(respostaDerivadaArea);

        add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(1127, 60));
        jPanel8.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel37.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel12.setText("f(x)");
        jPanel37.add(jLabel12, java.awt.BorderLayout.WEST);

        jfuncaoderivada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sen(lnx)", "tan(x).cos(x)", "3√e^secx" }));
        jPanel37.add(jfuncaoderivada, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel37, java.awt.BorderLayout.NORTH);

        jPanel47.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel38.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel13.setText("Tipo de Derivada");
        jPanel38.add(jLabel13, java.awt.BorderLayout.WEST);

        tipoDerivada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Superior", "Inferior", "Centrada" }));
        tipoDerivada.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel38.add(tipoDerivada, java.awt.BorderLayout.CENTER);

        jPanel47.add(jPanel38, java.awt.BorderLayout.WEST);

        jPanel46.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel43.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel41.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel15.setText("Incremento h/");
        jPanel41.add(jLabel15, java.awt.BorderLayout.WEST);

        taxaIncremento.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaIncremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaIncrementoActionPerformed(evt);
            }
        });
        jPanel41.add(taxaIncremento, java.awt.BorderLayout.CENTER);

        jPanel43.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel42.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel16.setText("X =");
        jPanel42.add(jLabel16, java.awt.BorderLayout.WEST);

        valorX.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel42.add(valorX, java.awt.BorderLayout.CENTER);

        jPanel43.add(jPanel42, java.awt.BorderLayout.WEST);

        jPanel46.add(jPanel43, java.awt.BorderLayout.WEST);

        jPanel44.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel40.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel17.setText("H inicial");
        jPanel40.add(jLabel17, java.awt.BorderLayout.WEST);

        hInicial.setMaximumSize(new java.awt.Dimension(50, 50));
        hInicial.setPreferredSize(new java.awt.Dimension(50, 20));
        hInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hInicialActionPerformed(evt);
            }
        });
        jPanel40.add(hInicial, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel40, java.awt.BorderLayout.CENTER);

        jPanel39.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel14.setText("Erro: 10^-");
        jPanel39.add(jLabel14, java.awt.BorderLayout.WEST);

        taxaErro.setMinimumSize(new java.awt.Dimension(50, 20));
        taxaErro.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaErroActionPerformed(evt);
            }
        });
        jPanel39.add(taxaErro, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel39, java.awt.BorderLayout.WEST);

        jPanel46.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel45.setLayout(new java.awt.BorderLayout(4, 4));

        jButton8.setText("Calcular");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton8, java.awt.BorderLayout.CENTER);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton7, java.awt.BorderLayout.EAST);

        jPanel46.add(jPanel45, java.awt.BorderLayout.EAST);

        jPanel47.add(jPanel46, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel47, java.awt.BorderLayout.SOUTH);

        add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel1.setText("Valor Final");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel1.add(campoResposta, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void taxaIncrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaIncrementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaIncrementoActionPerformed

    private void hInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hInicialActionPerformed

    private void taxaErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaErroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaErroActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        QuestoesDerivadas questoesDerivadas = new QuestoesDerivadas(jfuncaoderivada.getSelectedItem().toString(), tipoDerivada.getSelectedItem().toString(), Integer.parseInt(taxaIncremento.getText()), Double.parseDouble(valorX.getText()), Double.parseDouble(hInicial.getText()), Math.pow(10, -Double.parseDouble(taxaErro.getText())));
        String respostas = "";
        List<Double> resposta = questoesDerivadas.getResposta();
        for (Double point : resposta) {
            respostas+=point.toString()+"\n";
        }
        respostaDerivadaArea.setText(respostas);
        campoResposta.setText(resposta.get(resposta.size()-1).toString());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        switch (jfuncaoderivada.getSelectedItem().toString()) {
            case "sen(lnx)":
            valorX.setText("0.42");
            break;
            case "tan(x).cos(x)":
            valorX.setText("0.39");
            break;
            case "3√e^secx":
            valorX.setText("0.69");
            break;
        }
        taxaErro.setText("5");
        hInicial.setText("1");
        taxaIncremento.setText("2");
    }//GEN-LAST:event_jButton7ActionPerformed

    @Override
    public String toString() {
        String out  = "";
        out+= "Equação: "+jfuncaoderivada.getSelectedItem().toString();
        out+= "\nTipo: "+ tipoDerivada.getSelectedItem().toString();
        out+= "\nX inicial: "+ valorX.getText();
        out+= "\nIncremento h: "+ taxaIncremento.getText();
        out+= "\nErro: 10^-"+ taxaErro.getText();
        out+= "\nH inicial: "+ hInicial.getText();
        out+= "\nValores Calculados: \n"+ respostaDerivadaArea.getText();
        out+= "\nValor Final: "+ campoResposta.getText();
        out = out.replace(".", ",");
        return out;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoResposta;
    private javax.swing.JTextField hInicial;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox jfuncaoderivada;
    private javax.swing.JTextArea respostaDerivadaArea;
    private javax.swing.JTextField taxaErro;
    private javax.swing.JTextField taxaIncremento;
    private javax.swing.JComboBox tipoDerivada;
    private javax.swing.JTextField valorX;
    // End of variables declaration//GEN-END:variables
}
