/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao.panels;

import br.univali.model.minimos_quadrados.Point;
import br.univali.questoes.QuestoesDiferencial;
import java.util.List;

/**
 *
 * @author Alisson
 */
public class EulerPanel extends javax.swing.JPanel {

    /**
     * Creates new form EulerPanelk
     */
    public EulerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel67 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jfuncaodiferencial = new javax.swing.JComboBox();
        jPanel63 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tipoDiferencial = new javax.swing.JComboBox();
        jPanel62 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel64 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        xFinal2 = new javax.swing.JTextField();
        jPanel59 = new javax.swing.JPanel();
        xInicial2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        valorheuler = new javax.swing.JTextField();
        jPanel61 = new javax.swing.JPanel();
        yInicial = new javax.swing.JLabel();
        valory0 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        respx = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        respy = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new java.awt.BorderLayout(4, 4));

        jPanel67.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel18.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel22.setText("y'=");
        jPanel18.add(jLabel22, java.awt.BorderLayout.WEST);

        jfuncaodiferencial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "y-x", "2x^3-2xy", "y+x^(3/2)" }));
        jPanel18.add(jfuncaodiferencial, java.awt.BorderLayout.CENTER);

        jPanel67.add(jPanel18, java.awt.BorderLayout.NORTH);

        jPanel63.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel65.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel66.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel57.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel24.setText("Tipo de Metodo");
        jPanel57.add(jLabel24, java.awt.BorderLayout.WEST);

        tipoDiferencial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Euler", "Euler Modificado", "Euler Melhorado" }));
        jPanel57.add(tipoDiferencial, java.awt.BorderLayout.CENTER);

        jPanel66.add(jPanel57, java.awt.BorderLayout.CENTER);

        jPanel62.setLayout(new java.awt.BorderLayout(4, 4));

        jButton12.setText("Calcular");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel62.add(jButton12, java.awt.BorderLayout.CENTER);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel62.add(jButton11, java.awt.BorderLayout.EAST);

        jPanel66.add(jPanel62, java.awt.BorderLayout.EAST);

        jPanel65.add(jPanel66, java.awt.BorderLayout.SOUTH);

        jPanel64.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel64.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel68.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel60.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel60.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel26.setText("x Final");
        jPanel60.add(jLabel26, java.awt.BorderLayout.WEST);

        xFinal2.setMaximumSize(new java.awt.Dimension(50, 50));
        xFinal2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel60.add(xFinal2, java.awt.BorderLayout.CENTER);

        jPanel68.add(jPanel60, java.awt.BorderLayout.CENTER);

        jPanel59.setLayout(new java.awt.BorderLayout(4, 4));

        xInicial2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel59.add(xInicial2, java.awt.BorderLayout.CENTER);

        jLabel28.setText("x Inicial");
        jPanel59.add(jLabel28, java.awt.BorderLayout.WEST);

        jPanel68.add(jPanel59, java.awt.BorderLayout.WEST);

        jPanel64.add(jPanel68, java.awt.BorderLayout.CENTER);

        jPanel58.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel58.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel58.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel27.setText("h =");
        jPanel58.add(jLabel27, java.awt.BorderLayout.WEST);

        valorheuler.setPreferredSize(new java.awt.Dimension(150, 20));
        valorheuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorheulerActionPerformed(evt);
            }
        });
        jPanel58.add(valorheuler, java.awt.BorderLayout.CENTER);

        jPanel64.add(jPanel58, java.awt.BorderLayout.WEST);

        jPanel61.setLayout(new java.awt.BorderLayout(4, 4));

        yInicial.setText("y(0) =");
        jPanel61.add(yInicial, java.awt.BorderLayout.WEST);

        valory0.setPreferredSize(new java.awt.Dimension(150, 50));
        valory0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valory0ActionPerformed(evt);
            }
        });
        jPanel61.add(valory0, java.awt.BorderLayout.CENTER);

        jPanel64.add(jPanel61, java.awt.BorderLayout.EAST);

        jPanel65.add(jPanel64, java.awt.BorderLayout.NORTH);

        jPanel63.add(jPanel65, java.awt.BorderLayout.PAGE_START);

        jPanel67.add(jPanel63, java.awt.BorderLayout.SOUTH);

        add(jPanel67, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        respx.setColumns(20);
        respx.setRows(5);
        jScrollPane1.setViewportView(respx);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        respy.setColumns(20);
        respy.setRows(5);
        jScrollPane8.setViewportView(respy);

        jPanel1.add(jScrollPane8, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        QuestoesDiferencial questoesDiferencial =new QuestoesDiferencial(jfuncaodiferencial.getSelectedItem().toString(), tipoDiferencial.getSelectedItem().toString(), Double.parseDouble(valory0.getText()), Double.parseDouble(valorheuler.getText()), Double.parseDouble(xInicial2.getText()), Double.parseDouble(xFinal2.getText()));
        String pontosx = "";
        String pontosy = "";
        List<Point> points = questoesDiferencial.getResposta();
        for (Point point : points) {
            pontosx+=point.getX()+"\n";
            pontosy+=point.getY()+"\n";
        }
        respx.setText(pontosx);
        respy.setText(pontosy);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        switch (jfuncaodiferencial.getSelectedItem().toString()) {
            case "y-x":
            xInicial2.setText("0.0");
            xFinal2.setText("4.0");
            valory0.setText("2");
            valorheuler.setText("0.2");
            break;
            case "2x^3-2xy":
            xInicial2.setText("0.0");
            xFinal2.setText("3.0");
            valory0.setText("2");
            valorheuler.setText("0.15");
            break;
            case "y+x^(3/2)":
            xInicial2.setText("0.0");
            xFinal2.setText("2.0");
            valory0.setText("1");
            valorheuler.setText("0.1");
            break;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void valorheulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorheulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorheulerActionPerformed

    private void valory0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valory0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valory0ActionPerformed
    @Override
    public String toString() {
        String out  = "";
        out+= "Equação: "+jfuncaodiferencial.getSelectedItem().toString();
        out+= "\nh: "+ valorheuler.getText();
        out+= "\nX inicial: "+ xInicial2.getText();
        out+= "\nX final: "+ xFinal2.getText();
        out+= "\nY0: "+ valory0.getText();
        out+= "\nMétodo: "+ tipoDiferencial.getSelectedItem().toString();
        out+= "\nPontos: \n"+"X: \n"+respx.getText()+"Y: \n"+ respy.getText();
        out = out.replace(".", ",");
        return out;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JComboBox jfuncaodiferencial;
    private javax.swing.JTextArea respx;
    private javax.swing.JTextArea respy;
    private javax.swing.JComboBox tipoDiferencial;
    private javax.swing.JTextField valorheuler;
    private javax.swing.JTextField valory0;
    private javax.swing.JTextField xFinal2;
    private javax.swing.JTextField xInicial2;
    private javax.swing.JLabel yInicial;
    // End of variables declaration//GEN-END:variables
}
