/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao.panels;

import br.univali.model.gauss.Sistema;
import br.univali.visao.ViewAdapter;

/**
 *
 * @author Alisson
 */
public class GaussPanel extends javax.swing.JPanel {

    /**
     * Creates new form MetodoGauss
     */
    public GaussPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tamanhoMatrizAmpliada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMatriz = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        calcularGauss = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaMatrizEscalonada = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        vetorSolucao = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new java.awt.BorderLayout(4, 4));

        jPanel13.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel10.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel9.setPreferredSize(new java.awt.Dimension(1020, 25));
        jPanel9.setLayout(new java.awt.BorderLayout(4, 4));

        tamanhoMatrizAmpliada.setMinimumSize(new java.awt.Dimension(400, 20));
        tamanhoMatrizAmpliada.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel9.add(tamanhoMatrizAmpliada, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Digite o tamanho do Sistema");
        jPanel9.add(jLabel1, java.awt.BorderLayout.WEST);

        jPanel10.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Entre com a Matriz Ampliada, separando as posições com espaços");
        jPanel11.add(jLabel3, java.awt.BorderLayout.NORTH);

        areaMatriz.setColumns(20);
        areaMatriz.setRows(5);
        jScrollPane1.setViewportView(areaMatriz);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel12.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel19.setLayout(new java.awt.BorderLayout());

        calcularGauss.setText("Calcular");
        calcularGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularGaussActionPerformed(evt);
            }
        });
        jPanel19.add(calcularGauss, java.awt.BorderLayout.WEST);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel12.add(jPanel19, java.awt.BorderLayout.EAST);

        jLabel2.setText("Matriz ampliada escalonada e resposta");
        jPanel12.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel12, java.awt.BorderLayout.SOUTH);

        add(jPanel13, java.awt.BorderLayout.NORTH);

        jPanel16.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel14.setLayout(new java.awt.BorderLayout(4, 4));

        areaMatrizEscalonada.setColumns(20);
        areaMatrizEscalonada.setRows(5);
        jScrollPane3.setViewportView(areaMatrizEscalonada);

        jPanel14.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel15.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel11.setText("Vetor Solução");
        jPanel15.add(jLabel11, java.awt.BorderLayout.NORTH);

        vetorSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetorSolucaoActionPerformed(evt);
            }
        });
        jPanel15.add(vetorSolucao, java.awt.BorderLayout.SOUTH);

        jPanel16.add(jPanel15, java.awt.BorderLayout.SOUTH);

        add(jPanel16, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void calcularGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularGaussActionPerformed
        String matriz = areaMatriz.getText().toString();
        String tamanho = tamanhoMatrizAmpliada.getText().toString();

        Sistema sistema = new Sistema(ViewAdapter.stringToMatrix(tamanho, matriz));
        areaMatrizEscalonada.setText("Matriz Escalonada: \n"+ViewAdapter.matrixToString(sistema.getMatriz()));
        vetorSolucao.setText(ViewAdapter.vetorSolucaoToString(sistema.getVetorSolucao()));
    }//GEN-LAST:event_calcularGaussActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ajuda = "1 2 3\n2 3 5";
        areaMatriz.setText(ajuda);
        tamanhoMatrizAmpliada.setText("2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vetorSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetorSolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vetorSolucaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMatriz;
    private javax.swing.JTextArea areaMatrizEscalonada;
    private javax.swing.JButton calcularGauss;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField tamanhoMatrizAmpliada;
    private javax.swing.JTextField vetorSolucao;
    // End of variables declaration//GEN-END:variables
}
