/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao.panels;

import br.univali.questoes.QuestoesIntegrais;
import java.util.List;

/**
 *
 * @author Alisson
 */
public class IntegralPanel extends javax.swing.JPanel {

    /**
     * Creates new form IntegralPanelk
     */
    public IntegralPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        respostaIntegralArea = new javax.swing.JTextArea();
        jPanel56 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jfuncaointegral = new javax.swing.JComboBox();
        jPanel55 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        tipointegral1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel54 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        xFinal1 = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        xInicial1 = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        taxaErro1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        respostaFinal = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new java.awt.BorderLayout(4, 4));

        respostaIntegralArea.setColumns(20);
        respostaIntegralArea.setRows(5);
        jScrollPane7.setViewportView(respostaIntegralArea);

        add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel56.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel48.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel18.setText("f(x)");
        jPanel48.add(jLabel18, java.awt.BorderLayout.WEST);

        jfuncaointegral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "arcsen(3√x)", "cotan(x)+x^e", "√PIx" }));
        jPanel48.add(jfuncaointegral, java.awt.BorderLayout.CENTER);

        jPanel56.add(jPanel48, java.awt.BorderLayout.NORTH);

        jPanel55.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel49.setLayout(new java.awt.BorderLayout(4, 4));

        tipointegral1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simpson 1/3", "Simpson 3/8", "Trapézio" }));
        jPanel49.add(tipointegral1, java.awt.BorderLayout.CENTER);

        jLabel19.setText("Tipo de Integral");
        jPanel49.add(jLabel19, java.awt.BorderLayout.WEST);

        jPanel55.add(jPanel49, java.awt.BorderLayout.WEST);

        jPanel53.setLayout(new java.awt.BorderLayout(4, 4));

        jButton10.setText("Calcular");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel53.add(jButton10, java.awt.BorderLayout.CENTER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel53.add(jButton9, java.awt.BorderLayout.EAST);

        jPanel55.add(jPanel53, java.awt.BorderLayout.EAST);

        jPanel54.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel52.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel21.setText("Ponto Final");
        jPanel52.add(jLabel21, java.awt.BorderLayout.WEST);

        xFinal1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel52.add(xFinal1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel52, java.awt.BorderLayout.EAST);

        jPanel51.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel23.setText("Ponto Inicial");
        jPanel51.add(jLabel23, java.awt.BorderLayout.WEST);

        xInicial1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel51.add(xInicial1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel51, java.awt.BorderLayout.CENTER);

        jPanel50.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel20.setText("Erro: 10^-");
        jPanel50.add(jLabel20, java.awt.BorderLayout.WEST);

        taxaErro1.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaErro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaErro1ActionPerformed(evt);
            }
        });
        jPanel50.add(taxaErro1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel50, java.awt.BorderLayout.WEST);

        jPanel55.add(jPanel54, java.awt.BorderLayout.CENTER);

        jPanel56.add(jPanel55, java.awt.BorderLayout.SOUTH);

        add(jPanel56, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel1.setText("Valor Final");
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        respostaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respostaFinalActionPerformed(evt);
            }
        });
        jPanel1.add(respostaFinal, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        QuestoesIntegrais questoesIntegrais =  new QuestoesIntegrais(Double.parseDouble(xInicial1.getText()), Double.parseDouble(xFinal1.getText()), tipointegral1.getSelectedItem().toString(), jfuncaointegral.getSelectedItem().toString(), Math.pow(10, -Double.parseDouble(taxaErro1.getText())));
        String respostas = "";
        List<Double> resposta = questoesIntegrais.getResposta();
        for (Double valor : resposta) {
            respostas+=valor.toString()+"\n";
        }
        respostaIntegralArea.setText(respostas);
        respostaFinal.setText(resposta.get(resposta.size()-1).toString());
        
        System.out.println(this.toString());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        switch (jfuncaointegral.getSelectedItem().toString()) {
            case "arcsen(3√x)":
            xInicial1.setText("0.0");
            xFinal1.setText("0.24");
            break;
            case "cotan(x)+x^e":
            xInicial1.setText("0.5");
            xFinal1.setText("1.5");
            break;
            case "√PIx":
            xInicial1.setText("0.3");
            xFinal1.setText("3.0");
            break;
        }
        taxaErro1.setText("5");
    }//GEN-LAST:event_jButton9ActionPerformed

    @Override
    public String toString() {
        String out  = "";
        out+= "Equação: "+jfuncaointegral.getSelectedItem().toString();
        out+= "\nTipo: "+ tipointegral1.getSelectedItem().toString();
        out+= "\nX inicial: "+ xInicial1.getText();
        out+= "\nX final: "+ xFinal1.getText();
        out+= "\nErro: 10^-"+ taxaErro1.getText();
        out+= "\nValor Final: "+ respostaFinal.getText();
        
        return out;
    }
    
    
    
    private void taxaErro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaErro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaErro1ActionPerformed

    private void respostaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respostaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respostaFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox jfuncaointegral;
    private javax.swing.JTextField respostaFinal;
    private javax.swing.JTextArea respostaIntegralArea;
    private javax.swing.JTextField taxaErro1;
    private javax.swing.JComboBox tipointegral1;
    private javax.swing.JTextField xFinal1;
    private javax.swing.JTextField xInicial1;
    // End of variables declaration//GEN-END:variables
}
