/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao.panels;

import br.univali.model.interpolacao.EquationCalculator;
import br.univali.model.minimos_quadrados.MinimosQuadrados;
import br.univali.model.minimos_quadrados.Point;
import br.univali.visao.JGraph;
import br.univali.visao.UI;
import br.univali.visao.ViewAdapter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alisson
 */
public class MinimosQuadradosPanel extends javax.swing.JPanel {

    /**
     * Creates new form MinimosQuadradosPanel
     */
    public MinimosQuadradosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel27 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tipoFunacaoAproximacao = new javax.swing.JComboBox();
        jPanel24 = new javax.swing.JPanel();
        grauLabel = new javax.swing.JLabel();
        grauPolinomio = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ynsMMQ = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        xzesMMQ = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mMQFuncaoAproximada = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaMMQ = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setLayout(new java.awt.BorderLayout(4, 4));

        jPanel27.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel26.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel23.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel8.setText("Tipo de Funçao de Aproximação ");
        jPanel23.add(jLabel8, java.awt.BorderLayout.WEST);

        tipoFunacaoAproximacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Polinomial", "Geométrica", "ae^bx" }));
        tipoFunacaoAproximacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFunacaoAproximacaoActionPerformed(evt);
            }
        });
        jPanel23.add(tipoFunacaoAproximacao, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel23, java.awt.BorderLayout.WEST);

        jPanel24.setLayout(new java.awt.BorderLayout(4, 4));

        grauLabel.setText(" Grau do Polinômio");
        jPanel24.add(grauLabel, java.awt.BorderLayout.WEST);
        jPanel24.add(grauPolinomio, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel25.setLayout(new java.awt.BorderLayout(4, 4));

        jButton6.setText("Gráfico");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton6, java.awt.BorderLayout.WEST);

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton3, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel26.add(jPanel25, java.awt.BorderLayout.EAST);

        jPanel27.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel22.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel21.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel5.setText("Y dos Pontos");
        jPanel21.add(jLabel5, java.awt.BorderLayout.WEST);
        jPanel21.add(ynsMMQ, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel21, java.awt.BorderLayout.SOUTH);

        jPanel20.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel4.setText("X dos Pontos");
        jPanel20.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel20.add(xzesMMQ, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel20, java.awt.BorderLayout.NORTH);

        jPanel27.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        add(jPanel27, java.awt.BorderLayout.NORTH);

        jPanel29.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel28.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel7.setText("Função Aproximada");
        jPanel28.add(jLabel7, java.awt.BorderLayout.WEST);
        jPanel28.add(mMQFuncaoAproximada, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel28, java.awt.BorderLayout.SOUTH);

        areaMMQ.setEditable(false);
        areaMMQ.setColumns(20);
        areaMMQ.setRows(5);
        jScrollPane4.setViewportView(areaMMQ);

        jPanel29.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        add(jPanel29, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tipoFunacaoAproximacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFunacaoAproximacaoActionPerformed
        if(!tipoFunacaoAproximacao.getSelectedItem().toString().equals("Polinomial"))
        {
            grauLabel.setVisible(false);
            grauPolinomio.setVisible(false);
        }
        else
        {
            grauLabel.setVisible(true);
            grauPolinomio.setVisible(true);
        }
    }//GEN-LAST:event_tipoFunacaoAproximacaoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String stringXs=xzesMMQ.getText().toString();
        String stringYs=ynsMMQ.getText().toString();
        String grau;
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(grauPolinomio.isVisible())
        {
            grau=grauPolinomio.getText().toString();
        }
        else
        {
            grau="1";
        }
        List<Point> pontos = ViewAdapter.stringsToPoints(stringXs, stringYs);
        MinimosQuadrados minimosQuadrados = new MinimosQuadrados(pontos,Integer.parseInt(grau), tipoAproximacao);

        JGraph graph =new JGraph(ViewAdapter.stringsToPoints(stringXs, stringYs),EquationCalculator.calcularFuncao(minimosQuadrados.getList(),pontos.get(0).getX(), pontos.get(pontos.size()-1).getX()+1, 1.0, tipoAproximacao));
        try {
            graph.showHTML();
        } catch (Exception ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String stringXs=xzesMMQ.getText().toString();
        String stringYs=ynsMMQ.getText().toString();
        String grau;
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(grauPolinomio.isVisible())
        {
            grau=grauPolinomio.getText().toString();
        }
        else
        {
            grau="1";
        }
        MinimosQuadrados minimosQuadrados = new MinimosQuadrados(ViewAdapter.stringsToPoints(stringXs, stringYs),Integer.parseInt(grau), tipoAproximacao);
        String tesxtoResposta="";
        tesxtoResposta+= ViewAdapter.doubleVectorToString(minimosQuadrados.getList());
        tesxtoResposta+="\nMatriz Inicial: \n";
        tesxtoResposta+=ViewAdapter.matrixToString(minimosQuadrados.getMatrizInicial());
        tesxtoResposta+="\nMatriz Escalonada: \n";
        tesxtoResposta+=ViewAdapter.matrixToString(minimosQuadrados.getMatrizEscalonada());
        areaMMQ.setText(tesxtoResposta);
        mMQFuncaoAproximada.setText(ViewAdapter.doubleVectorEquation(minimosQuadrados.getList(),tipoAproximacao));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(tipoAproximacao.equals("Polinomial"))
        {
            xzesMMQ.setText("-2 -1 0 1 2");
            ynsMMQ.setText("0 0 -1 0 7");
            grauPolinomio.setText("1");
        }
        else if(tipoAproximacao.equals("Geométrica")){
            xzesMMQ.setText("0,1 0,5 1 2 3");
            ynsMMQ.setText("0,005 0,5 4 30 110");
        }
        else if(tipoAproximacao.equals("ae^bx")){
            xzesMMQ.setText("2 5 8 11 14 17 27 31 41 44");
            ynsMMQ.setText("94,8 89,7 81,3 74,9 68,7 64,0 49,3 44,0 39,1 31,6");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    @Override
    public String toString() {
        String out  = "";
        out+= "X: "+xzesMMQ.getText();
        out+= "\nY: "+ ynsMMQ.getText();
        out+= "\nTipo: "+ tipoFunacaoAproximacao.getSelectedItem().toString();
        out+= "\nGrau: "+ grauLabel.getText();
        out+= "\nSolução: "+ areaMMQ.getText();
        out+= "\nFunção Aproximada: "+ mMQFuncaoAproximada.getText();
        out = out.replace(".", ",");
        return out;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMMQ;
    private javax.swing.JLabel grauLabel;
    private javax.swing.JTextField grauPolinomio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField mMQFuncaoAproximada;
    private javax.swing.JComboBox tipoFunacaoAproximacao;
    private javax.swing.JTextField xzesMMQ;
    private javax.swing.JTextField ynsMMQ;
    // End of variables declaration//GEN-END:variables
}
