/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.visao;

import com.alee.laf.WebLookAndFeel;
import br.univali.model.gauss.Sistema;
import br.univali.model.interpolacao.EquationCalculator;
import br.univali.model.interpolacao.Interpolacao;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import br.univali.model.minimos_quadrados.MinimosQuadrados;
import br.univali.model.minimos_quadrados.Point;
import br.univali.questoes.QuestoesDerivadas;
import br.univali.questoes.QuestoesDiferencial;
import br.univali.questoes.QuestoesIntegrais;

/**
 *
 * @author 5663296
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        areaMatrizEscalonada.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jTabbedGauss = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tamanhoMatrizAmpliada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMatriz = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        calcularGauss = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaMatrizEscalonada = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        vetorSolucao = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tipoFunacaoAproximacao = new javax.swing.JComboBox();
        jPanel24 = new javax.swing.JPanel();
        grauLabel = new javax.swing.JLabel();
        grauPolinomio = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ynsMMQ = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        xzesMMQ = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        mMQFuncaoAproximada = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaMMQ = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaInterpolacao = new javax.swing.JTextArea();
        jPanel36 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        xzesInterpolacao = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        yonsInterpolacao = new javax.swing.JTextField();
        jPanel34 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tipoFuncaoInterpolacao = new javax.swing.JComboBox();
        jPanel33 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        respostaDerivadaArea = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jfuncaoderivada = new javax.swing.JComboBox();
        jPanel47 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tipoDerivada = new javax.swing.JComboBox();
        jPanel46 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        taxaIncremento = new javax.swing.JTextField();
        jPanel42 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        valorX = new javax.swing.JTextField();
        jPanel44 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        hInicial = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        taxaErro = new javax.swing.JTextField();
        jPanel45 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        respostaIntegralArea = new javax.swing.JTextArea();
        jPanel56 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jfuncaointegral = new javax.swing.JComboBox();
        jPanel55 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        tipointegral1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel54 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        xFinal1 = new javax.swing.JTextField();
        jPanel51 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        xInicial1 = new javax.swing.JTextField();
        jPanel50 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        taxaErro1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        respostaDiferencialArea = new javax.swing.JTextArea();
        jPanel67 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jfuncaodiferencial = new javax.swing.JComboBox();
        jPanel63 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tipoDiferencial = new javax.swing.JComboBox();
        jPanel62 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel64 = new javax.swing.JPanel();
        jPanel68 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        xFinal2 = new javax.swing.JTextField();
        jPanel59 = new javax.swing.JPanel();
        xInicial2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        valorheuler = new javax.swing.JTextField();
        jPanel61 = new javax.swing.JPanel();
        yInicial = new javax.swing.JLabel();
        valory0 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Omega Power & Knuckles Calculator");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.BorderLayout(20, 20));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel2.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel17.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel13.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel10.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel9.setPreferredSize(new java.awt.Dimension(1020, 25));
        jPanel9.setLayout(new java.awt.BorderLayout(4, 4));

        tamanhoMatrizAmpliada.setMinimumSize(new java.awt.Dimension(400, 20));
        tamanhoMatrizAmpliada.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel9.add(tamanhoMatrizAmpliada, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Digite o tamanho do Sistema");
        jPanel9.add(jLabel1, java.awt.BorderLayout.WEST);

        jPanel10.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Entre com a Matriz Ampliada, separando as posições com espaços");
        jPanel11.add(jLabel3, java.awt.BorderLayout.NORTH);

        areaMatriz.setColumns(20);
        areaMatriz.setRows(5);
        jScrollPane1.setViewportView(areaMatriz);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel12.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel19.setLayout(new java.awt.BorderLayout());

        calcularGauss.setText("Calcular");
        calcularGauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularGaussActionPerformed(evt);
            }
        });
        jPanel19.add(calcularGauss, java.awt.BorderLayout.WEST);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel12.add(jPanel19, java.awt.BorderLayout.EAST);

        jLabel2.setText("Matriz ampliada escalonada e resposta");
        jPanel12.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel13.add(jPanel12, java.awt.BorderLayout.SOUTH);

        jPanel17.add(jPanel13, java.awt.BorderLayout.NORTH);

        jPanel16.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel14.setLayout(new java.awt.BorderLayout(4, 4));

        areaMatrizEscalonada.setColumns(20);
        areaMatrizEscalonada.setRows(5);
        jScrollPane3.setViewportView(areaMatrizEscalonada);

        jPanel14.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel15.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel11.setText("Vetor Solução");
        jPanel15.add(jLabel11, java.awt.BorderLayout.NORTH);

        vetorSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vetorSolucaoActionPerformed(evt);
            }
        });
        jPanel15.add(vetorSolucao, java.awt.BorderLayout.SOUTH);

        jPanel16.add(jPanel15, java.awt.BorderLayout.SOUTH);

        jPanel17.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17, java.awt.BorderLayout.CENTER);

        jTabbedGauss.addTab("Metodo de Gauss", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel3.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel27.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel26.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel23.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel8.setText("Tipo de Funçao de Aproximação ");
        jPanel23.add(jLabel8, java.awt.BorderLayout.WEST);

        tipoFunacaoAproximacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Polinomial", "Geométrica", "ae^bx" }));
        tipoFunacaoAproximacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoFunacaoAproximacaoActionPerformed(evt);
            }
        });
        jPanel23.add(tipoFunacaoAproximacao, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel23, java.awt.BorderLayout.WEST);

        jPanel24.setLayout(new java.awt.BorderLayout(4, 4));

        grauLabel.setText(" Grau do Polinômio");
        jPanel24.add(grauLabel, java.awt.BorderLayout.WEST);
        jPanel24.add(grauPolinomio, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel25.setLayout(new java.awt.BorderLayout(4, 4));

        jButton6.setText("Gráfico");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton6, java.awt.BorderLayout.WEST);

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton3, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel26.add(jPanel25, java.awt.BorderLayout.EAST);

        jPanel27.add(jPanel26, java.awt.BorderLayout.CENTER);

        jPanel22.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel21.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel5.setText("Y dos Pontos");
        jPanel21.add(jLabel5, java.awt.BorderLayout.WEST);
        jPanel21.add(ynsMMQ, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel21, java.awt.BorderLayout.SOUTH);

        jPanel20.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel4.setText("X dos Pontos");
        jPanel20.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel20.add(xzesMMQ, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel20, java.awt.BorderLayout.NORTH);

        jPanel27.add(jPanel22, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel27, java.awt.BorderLayout.NORTH);

        jPanel29.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel28.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel7.setText("Função Aproximada");
        jPanel28.add(jLabel7, java.awt.BorderLayout.WEST);
        jPanel28.add(mMQFuncaoAproximada, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel28, java.awt.BorderLayout.SOUTH);

        areaMMQ.setEditable(false);
        areaMMQ.setColumns(20);
        areaMMQ.setRows(5);
        jScrollPane4.setViewportView(areaMMQ);

        jPanel29.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel29, java.awt.BorderLayout.CENTER);

        jTabbedGauss.addTab("Metodos dos Minimos Quadrados", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel4.setLayout(new java.awt.BorderLayout(4, 4));

        areaInterpolacao.setColumns(20);
        areaInterpolacao.setRows(5);
        jScrollPane5.setViewportView(areaInterpolacao);

        jPanel4.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanel36.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel35.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel30.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel6.setText("X dos pontos");
        jPanel30.add(jLabel6, java.awt.BorderLayout.WEST);
        jPanel30.add(xzesInterpolacao, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel30, java.awt.BorderLayout.NORTH);

        jPanel31.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel9.setText("Y dos pontos");
        jPanel31.add(jLabel9, java.awt.BorderLayout.WEST);
        jPanel31.add(yonsInterpolacao, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel31, java.awt.BorderLayout.SOUTH);

        jPanel36.add(jPanel35, java.awt.BorderLayout.NORTH);

        jPanel34.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel32.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel10.setText("Tipo de Interpolação");
        jPanel32.add(jLabel10, java.awt.BorderLayout.WEST);

        tipoFuncaoInterpolacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Polinomial", "SPline" }));
        jPanel32.add(tipoFuncaoInterpolacao, java.awt.BorderLayout.CENTER);

        jPanel34.add(jPanel32, java.awt.BorderLayout.CENTER);

        jPanel33.setLayout(new java.awt.BorderLayout(4, 4));

        jToggleButton1.setText("Grafico");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel33.add(jToggleButton1, java.awt.BorderLayout.WEST);

        jButton5.setText("Calcular");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel33.add(jButton5, java.awt.BorderLayout.CENTER);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel33.add(jButton4, java.awt.BorderLayout.EAST);

        jPanel34.add(jPanel33, java.awt.BorderLayout.EAST);

        jPanel36.add(jPanel34, java.awt.BorderLayout.SOUTH);

        jPanel4.add(jPanel36, java.awt.BorderLayout.NORTH);

        jTabbedGauss.addTab("Interpolação", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel5.setLayout(new java.awt.BorderLayout(4, 4));

        respostaDerivadaArea.setColumns(20);
        respostaDerivadaArea.setRows(5);
        jScrollPane6.setViewportView(respostaDerivadaArea);

        jPanel5.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel8.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(1127, 60));
        jPanel8.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel37.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel12.setText("f(x)");
        jPanel37.add(jLabel12, java.awt.BorderLayout.WEST);

        jfuncaoderivada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sen(lnx)", "tan(x).cos(x)", "3√e^secx" }));
        jPanel37.add(jfuncaoderivada, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel37, java.awt.BorderLayout.NORTH);

        jPanel47.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel38.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel13.setText("Tipo de Derivada");
        jPanel38.add(jLabel13, java.awt.BorderLayout.WEST);

        tipoDerivada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Superior", "Inferior", "Centrada" }));
        tipoDerivada.setPreferredSize(new java.awt.Dimension(75, 20));
        jPanel38.add(tipoDerivada, java.awt.BorderLayout.CENTER);

        jPanel47.add(jPanel38, java.awt.BorderLayout.WEST);

        jPanel46.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel43.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel41.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel15.setText("Incremento h/");
        jPanel41.add(jLabel15, java.awt.BorderLayout.WEST);

        taxaIncremento.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaIncremento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaIncrementoActionPerformed(evt);
            }
        });
        jPanel41.add(taxaIncremento, java.awt.BorderLayout.CENTER);

        jPanel43.add(jPanel41, java.awt.BorderLayout.CENTER);

        jPanel42.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel16.setText("X =");
        jPanel42.add(jLabel16, java.awt.BorderLayout.WEST);

        valorX.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel42.add(valorX, java.awt.BorderLayout.CENTER);

        jPanel43.add(jPanel42, java.awt.BorderLayout.WEST);

        jPanel46.add(jPanel43, java.awt.BorderLayout.WEST);

        jPanel44.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel40.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel17.setText("H inicial");
        jPanel40.add(jLabel17, java.awt.BorderLayout.WEST);

        hInicial.setMaximumSize(new java.awt.Dimension(50, 50));
        hInicial.setPreferredSize(new java.awt.Dimension(50, 20));
        hInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hInicialActionPerformed(evt);
            }
        });
        jPanel40.add(hInicial, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel40, java.awt.BorderLayout.CENTER);

        jPanel39.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel14.setText("Erro: 10^-");
        jPanel39.add(jLabel14, java.awt.BorderLayout.WEST);

        taxaErro.setMinimumSize(new java.awt.Dimension(50, 20));
        taxaErro.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaErroActionPerformed(evt);
            }
        });
        jPanel39.add(taxaErro, java.awt.BorderLayout.CENTER);

        jPanel44.add(jPanel39, java.awt.BorderLayout.WEST);

        jPanel46.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel45.setLayout(new java.awt.BorderLayout(4, 4));

        jButton8.setText("Calcular");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton8, java.awt.BorderLayout.CENTER);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel45.add(jButton7, java.awt.BorderLayout.EAST);

        jPanel46.add(jPanel45, java.awt.BorderLayout.EAST);

        jPanel47.add(jPanel46, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel47, java.awt.BorderLayout.SOUTH);

        jPanel5.add(jPanel8, java.awt.BorderLayout.NORTH);

        jTabbedGauss.addTab("Derivada Numérica", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel6.setLayout(new java.awt.BorderLayout(4, 4));

        respostaIntegralArea.setColumns(20);
        respostaIntegralArea.setRows(5);
        jScrollPane7.setViewportView(respostaIntegralArea);

        jPanel6.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanel56.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel48.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel18.setText("f(x)");
        jPanel48.add(jLabel18, java.awt.BorderLayout.WEST);

        jfuncaointegral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "arcsen(3√x)", "cotan(x)+x^e", "√PIx" }));
        jPanel48.add(jfuncaointegral, java.awt.BorderLayout.CENTER);

        jPanel56.add(jPanel48, java.awt.BorderLayout.NORTH);

        jPanel55.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel49.setLayout(new java.awt.BorderLayout(4, 4));

        tipointegral1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simpson 1/3", "Simpson 3/8", "Trapézio" }));
        jPanel49.add(tipointegral1, java.awt.BorderLayout.CENTER);

        jLabel19.setText("Tipo de Integral");
        jPanel49.add(jLabel19, java.awt.BorderLayout.WEST);

        jPanel55.add(jPanel49, java.awt.BorderLayout.WEST);

        jPanel53.setLayout(new java.awt.BorderLayout(4, 4));

        jButton10.setText("Calcular");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel53.add(jButton10, java.awt.BorderLayout.CENTER);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel53.add(jButton9, java.awt.BorderLayout.EAST);

        jPanel55.add(jPanel53, java.awt.BorderLayout.EAST);

        jPanel54.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel52.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel21.setText("Ponto Final");
        jPanel52.add(jLabel21, java.awt.BorderLayout.WEST);

        xFinal1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel52.add(xFinal1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel52, java.awt.BorderLayout.EAST);

        jPanel51.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel23.setText("Ponto Inicial");
        jPanel51.add(jLabel23, java.awt.BorderLayout.WEST);

        xInicial1.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel51.add(xInicial1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel51, java.awt.BorderLayout.CENTER);

        jPanel50.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel20.setText("Erro: 10^-");
        jPanel50.add(jLabel20, java.awt.BorderLayout.WEST);

        taxaErro1.setPreferredSize(new java.awt.Dimension(50, 20));
        taxaErro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxaErro1ActionPerformed(evt);
            }
        });
        jPanel50.add(taxaErro1, java.awt.BorderLayout.CENTER);

        jPanel54.add(jPanel50, java.awt.BorderLayout.WEST);

        jPanel55.add(jPanel54, java.awt.BorderLayout.CENTER);

        jPanel56.add(jPanel55, java.awt.BorderLayout.SOUTH);

        jPanel6.add(jPanel56, java.awt.BorderLayout.NORTH);

        jTabbedGauss.addTab("Integral Numérica", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        respostaDiferencialArea.setColumns(20);
        respostaDiferencialArea.setRows(5);
        jScrollPane8.setViewportView(respostaDiferencialArea);

        jPanel7.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jPanel67.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel18.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel22.setText("y'=");
        jPanel18.add(jLabel22, java.awt.BorderLayout.WEST);

        jfuncaodiferencial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "y-x", "2x^3-2xy", "y+x^(3/2)" }));
        jPanel18.add(jfuncaodiferencial, java.awt.BorderLayout.CENTER);

        jPanel67.add(jPanel18, java.awt.BorderLayout.NORTH);

        jPanel63.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel65.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel66.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel57.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel24.setText("Tipo de Metodo");
        jPanel57.add(jLabel24, java.awt.BorderLayout.WEST);

        tipoDiferencial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Euler", "Euler Modificado", "Euler Melhorado" }));
        jPanel57.add(tipoDiferencial, java.awt.BorderLayout.CENTER);

        jPanel66.add(jPanel57, java.awt.BorderLayout.CENTER);

        jPanel62.setLayout(new java.awt.BorderLayout(4, 4));

        jButton12.setText("Calcular");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel62.add(jButton12, java.awt.BorderLayout.CENTER);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/univali/resources/interrogation.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel62.add(jButton11, java.awt.BorderLayout.EAST);

        jPanel66.add(jPanel62, java.awt.BorderLayout.EAST);

        jPanel65.add(jPanel66, java.awt.BorderLayout.SOUTH);

        jPanel64.setPreferredSize(new java.awt.Dimension(10, 25));
        jPanel64.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel68.setPreferredSize(null);
        jPanel68.setLayout(new java.awt.BorderLayout(4, 4));

        jPanel60.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel60.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel26.setText("x Final");
        jPanel60.add(jLabel26, java.awt.BorderLayout.WEST);

        xFinal2.setMaximumSize(new java.awt.Dimension(50, 50));
        xFinal2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanel60.add(xFinal2, java.awt.BorderLayout.CENTER);

        jPanel68.add(jPanel60, java.awt.BorderLayout.CENTER);

        jPanel59.setLayout(new java.awt.BorderLayout(4, 4));

        xInicial2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel59.add(xInicial2, java.awt.BorderLayout.CENTER);

        jLabel28.setText("x Inicial");
        jPanel59.add(jLabel28, java.awt.BorderLayout.WEST);

        jPanel68.add(jPanel59, java.awt.BorderLayout.WEST);

        jPanel64.add(jPanel68, java.awt.BorderLayout.CENTER);

        jPanel58.setMaximumSize(new java.awt.Dimension(50, 50));
        jPanel58.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel58.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel27.setText("h =");
        jPanel58.add(jLabel27, java.awt.BorderLayout.WEST);

        valorheuler.setPreferredSize(new java.awt.Dimension(150, 20));
        valorheuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorheulerActionPerformed(evt);
            }
        });
        jPanel58.add(valorheuler, java.awt.BorderLayout.CENTER);

        jPanel64.add(jPanel58, java.awt.BorderLayout.WEST);

        jPanel61.setLayout(new java.awt.BorderLayout(4, 4));

        yInicial.setText("y(0) =");
        jPanel61.add(yInicial, java.awt.BorderLayout.WEST);

        valory0.setPreferredSize(new java.awt.Dimension(150, 50));
        valory0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valory0ActionPerformed(evt);
            }
        });
        jPanel61.add(valory0, java.awt.BorderLayout.CENTER);

        jPanel64.add(jPanel61, java.awt.BorderLayout.EAST);

        jPanel65.add(jPanel64, java.awt.BorderLayout.NORTH);

        jPanel63.add(jPanel65, java.awt.BorderLayout.PAGE_START);

        jPanel67.add(jPanel63, java.awt.BorderLayout.SOUTH);

        jPanel7.add(jPanel67, java.awt.BorderLayout.NORTH);

        jTabbedGauss.addTab("Equação Diferencial de Euler", jPanel7);

        jPanel1.add(jTabbedGauss, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Gerar Arquivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ajuda = "1 2 3\n2 3 5";
        areaMatriz.setText(ajuda);
        tamanhoMatrizAmpliada.setText("2");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void calcularGaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularGaussActionPerformed
        String matriz = areaMatriz.getText().toString();
        String tamanho = tamanhoMatrizAmpliada.getText().toString();
        
        Sistema sistema = new Sistema(ViewAdapter.stringToMatrix(tamanho, matriz));
        areaMatrizEscalonada.setText("Matriz Escalonada: \n"+ViewAdapter.matrixToString(sistema.getMatriz()));
        vetorSolucao.setText(ViewAdapter.vetorSolucaoToString(sistema.getVetorSolucao()));
    }//GEN-LAST:event_calcularGaussActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(tipoAproximacao.equals("Polinomial"))
        {
            xzesMMQ.setText("-2 -1 0 1 2");
            ynsMMQ.setText("0 0 -1 0 7");
            grauPolinomio.setText("1");
        }
        else if(tipoAproximacao.equals("Geométrica")){
            xzesMMQ.setText("0,1 0,5 1 2 3");
            ynsMMQ.setText("0,005 0,5 4 30 110");
        }
        else if(tipoAproximacao.equals("ae^bx")){
            xzesMMQ.setText("2 5 8 11 14 17 27 31 41 44");
            ynsMMQ.setText("94,8 89,7 81,3 74,9 68,7 64,0 49,3 44,0 39,1 31,6");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String stringXs=xzesMMQ.getText().toString();
        String stringYs=ynsMMQ.getText().toString();
        String grau;
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(grauPolinomio.isVisible())
        {
            grau=grauPolinomio.getText().toString();
        }
        else
        {
            grau="1";
        }
        MinimosQuadrados minimosQuadrados = new MinimosQuadrados(ViewAdapter.stringsToPoints(stringXs, stringYs),Integer.parseInt(grau), tipoAproximacao);
        String tesxtoResposta="";
        tesxtoResposta+= ViewAdapter.doubleVectorToString(minimosQuadrados.getList());
        tesxtoResposta+="\nMatriz Inicial: \n";
        tesxtoResposta+=ViewAdapter.matrixToString(minimosQuadrados.getMatrizInicial());
        tesxtoResposta+="\nMatriz Escalonada: \n";
        tesxtoResposta+=ViewAdapter.matrixToString(minimosQuadrados.getMatrizEscalonada());
        areaMMQ.setText(tesxtoResposta);
        mMQFuncaoAproximada.setText(ViewAdapter.doubleVectorEquation(minimosQuadrados.getList(),tipoAproximacao));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tipoFunacaoAproximacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoFunacaoAproximacaoActionPerformed
        if(!tipoFunacaoAproximacao.getSelectedItem().toString().equals("Polinomial"))
        {
            grauLabel.setVisible(false);
            grauPolinomio.setVisible(false);
        }
        else
        {
            grauLabel.setVisible(true);
            grauPolinomio.setVisible(true);
        }
    }//GEN-LAST:event_tipoFunacaoAproximacaoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String stringXs=xzesInterpolacao.getText().toString();
        String stringYs=yonsInterpolacao.getText().toString();
        String tipodeInterpolacao = tipoFuncaoInterpolacao.getSelectedItem().toString();
        Interpolacao interpolacao= new Interpolacao(ViewAdapter.stringsToPoints(stringXs, stringYs), tipodeInterpolacao);
        String textoResposta="";
        
        if(tipodeInterpolacao.equals("SPline"))
        {
           textoResposta+=ViewAdapter.doubleVectorEquations(interpolacao.getList(), interpolacao.getFunctions());
        }
        else
        {
            textoResposta += ViewAdapter.doubleVectorToString(interpolacao.getList());
        }
        textoResposta+="\nMatriz Inicial: \n";
        textoResposta+=ViewAdapter.matrixToString(interpolacao.getMatrizInicial());
        textoResposta+="\nMatriz Escalonada: \n";
        textoResposta+=ViewAdapter.matrixToString(interpolacao.getMatrizEscalonada());
        areaInterpolacao.setText(textoResposta);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tipoInterpolacao = tipoFuncaoInterpolacao.getSelectedItem().toString();
        if(tipoInterpolacao.equals("SPline")){
            xzesInterpolacao.setText("1 3 5 10 12 15 18 20 30");
            yonsInterpolacao.setText("2 4 6 20 2 24 88 38 1");
        }
        else if(tipoInterpolacao.equals("Polinomial"))
        {
            xzesInterpolacao.setText("1 3 4 5");
            yonsInterpolacao.setText("-1 0 1 1 -1");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String stringXs=xzesInterpolacao.getText().toString();
        String stringYs=yonsInterpolacao.getText().toString();
        
        JGraph graph =new JGraph(ViewAdapter.stringsToPoints(stringXs, stringYs),ViewAdapter.stringsToPoints(stringXs, stringYs));
        try {
            graph.showHTML();
        } catch (Exception ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void vetorSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vetorSolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vetorSolucaoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String stringXs=xzesMMQ.getText().toString();
        String stringYs=ynsMMQ.getText().toString();
        String grau;
        String tipoAproximacao = tipoFunacaoAproximacao.getSelectedItem().toString();
        if(grauPolinomio.isVisible())
        {
            grau=grauPolinomio.getText().toString();
        }
        else
        {
            grau="1";
        }
        List<Point> pontos = ViewAdapter.stringsToPoints(stringXs, stringYs);
        MinimosQuadrados minimosQuadrados = new MinimosQuadrados(pontos,Integer.parseInt(grau), tipoAproximacao);
        
        JGraph graph =new JGraph(ViewAdapter.stringsToPoints(stringXs, stringYs),EquationCalculator.calcularFuncao(minimosQuadrados.getList(),pontos.get(0).getX(), pontos.get(pontos.size()-1).getX()+1, 1.0, tipoAproximacao));
        try {
            graph.showHTML();
        } catch (Exception ex) {
            Logger.getLogger(UI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void taxaErro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaErro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaErro1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        switch (jfuncaointegral.getSelectedItem().toString()) {
            case "arcsen(3√x)":
                xInicial1.setText("0.0");
                xFinal1.setText("0.24");
                break;
            case "cotan(x)+x^e":
                xInicial1.setText("0.5");
                xFinal1.setText("1.5");  
                break;
            case "√PIx":
                xInicial1.setText("0.3");
                xFinal1.setText("3.0");
                break;
        }
        taxaErro1.setText("5");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        QuestoesIntegrais questoesIntegrais =  new QuestoesIntegrais(Double.parseDouble(xInicial1.getText()), Double.parseDouble(xFinal1.getText()), tipointegral1.getSelectedItem().toString(), jfuncaointegral.getSelectedItem().toString(), Double.parseDouble(taxaErro1.getText()));
        respostaIntegralArea.setText(questoesIntegrais.getResposta().toString());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        switch (jfuncaodiferencial.getSelectedItem().toString()) {
            case "y-x":
                xInicial2.setText("0.0");
                xFinal2.setText("4.0");
                valory0.setText("2");
                valorheuler.setText("0.2");
                break;
            case "2x^3-2xy":
                xInicial2.setText("0.0");
                xFinal2.setText("3.0");  
                valory0.setText("2");
                valorheuler.setText("0.15");
                break;
            case "y+x^(3/2)":
                xInicial2.setText("0.0");
                xFinal2.setText("2.0");
                valory0.setText("1");
                valorheuler.setText("0.1");
                break;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        QuestoesDiferencial questoesDiferencial =new QuestoesDiferencial(jfuncaodiferencial.getSelectedItem().toString(), tipoDiferencial.getSelectedItem().toString(), Double.parseDouble(valory0.getText()), Double.parseDouble(valorheuler.getText()), Double.parseDouble(xInicial2.getText()), Double.parseDouble(xFinal2.getText()));
        String pontos = "";
        List<Point> points = questoesDiferencial.getResposta();
        for (Point point : points) {
            pontos+=point.toString()+"\n";
        }
        respostaDiferencialArea.setText(pontos);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void taxaErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaErroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaErroActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        switch (jfuncaoderivada.getSelectedItem().toString()) {
            case "sen(lnx)":
            valorX.setText("0.42");
            break;
            case "tan(x).cos(x)":
            valorX.setText("0.39");
            break;
            case "3√e^secx":
            valorX.setText("0.69");
            break;
        }
        taxaErro.setText("5");
        hInicial.setText("1");
        taxaIncremento.setText("2");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        QuestoesDerivadas questoesDerivadas = new QuestoesDerivadas(jfuncaoderivada.getSelectedItem().toString(), tipoDerivada.getSelectedItem().toString(), Integer.parseInt(taxaIncremento.getText()), Double.parseDouble(valorX.getText()), Double.parseDouble(hInicial.getText()), Math.pow(10, Double.parseDouble(taxaErro.getText())));
        respostaDerivadaArea.setText(questoesDerivadas.getResposta().toString());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void hInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hInicialActionPerformed

    private void valory0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valory0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valory0ActionPerformed

    private void valorheulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorheulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorheulerActionPerformed

    private void taxaIncrementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxaIncrementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxaIncrementoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void erroComentario()
    {
        JOptionPane.showMessageDialog(this, "Apaga o Comentário Jovin!!");
    }
    
    private void erroVazio()
    {
        JOptionPane.showMessageDialog(this, "Sem nada não dá de calcular né...");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new WebLookAndFeel());
        } catch (Exception ex) {
            
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaInterpolacao;
    private javax.swing.JTextArea areaMMQ;
    private javax.swing.JTextArea areaMatriz;
    private javax.swing.JTextArea areaMatrizEscalonada;
    private javax.swing.JButton calcularGauss;
    private javax.swing.JLabel grauLabel;
    private javax.swing.JTextField grauPolinomio;
    private javax.swing.JTextField hInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedGauss;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JComboBox jfuncaoderivada;
    private javax.swing.JComboBox jfuncaodiferencial;
    private javax.swing.JComboBox jfuncaointegral;
    private javax.swing.JTextField mMQFuncaoAproximada;
    private javax.swing.JTextArea respostaDerivadaArea;
    private javax.swing.JTextArea respostaDiferencialArea;
    private javax.swing.JTextArea respostaIntegralArea;
    private javax.swing.JTextField tamanhoMatrizAmpliada;
    private javax.swing.JTextField taxaErro;
    private javax.swing.JTextField taxaErro1;
    private javax.swing.JTextField taxaIncremento;
    private javax.swing.JComboBox tipoDerivada;
    private javax.swing.JComboBox tipoDiferencial;
    private javax.swing.JComboBox tipoFunacaoAproximacao;
    private javax.swing.JComboBox tipoFuncaoInterpolacao;
    private javax.swing.JComboBox tipointegral1;
    private javax.swing.JTextField valorX;
    private javax.swing.JTextField valorheuler;
    private javax.swing.JTextField valory0;
    private javax.swing.JTextField vetorSolucao;
    private javax.swing.JTextField xFinal1;
    private javax.swing.JTextField xFinal2;
    private javax.swing.JTextField xInicial1;
    private javax.swing.JTextField xInicial2;
    private javax.swing.JTextField xzesInterpolacao;
    private javax.swing.JTextField xzesMMQ;
    private javax.swing.JLabel yInicial;
    private javax.swing.JTextField ynsMMQ;
    private javax.swing.JTextField yonsInterpolacao;
    // End of variables declaration//GEN-END:variables
}
